apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "keycloak-service.selectorLabels" . | nindent 4 }}
    eks.amazonaws.com/fargate-profile: sbrc-registry
