apiVersion: v1
kind: ConfigMap
metadata:
  name: sbrc-bulk-issuance-config
  namespace: sbrc-registry
data:
  REGISTRY_BASE_URL: http://sbrc-registry:8081
  DATABASE_HOST: sbrc-pgsql-db.cluster-cveklit2rj4m.ap-south-1.rds.amazonaws.com
  DATABASE_PORT: "5432"
  DATABASE_USER: postgres
  DATABASE_NAME: registry
  KEYCLOAK_URL: http://sbrc-registry-keycloak-service:8080/auth
  KEYCLOAK_REALM: sunbird-rc