apiVersion: v1
kind: Service
metadata:
  name: sbrc-bulk-issuance
  namespace: sbrc-registry
spec:
  ports:
   - port: 5665
     protocol: TCP
     targetPort: 5665
  selector:
    name: sunbird-rc-bulk-issuance
    eks.amazonaws.com/fargate-profile: sbrc-registry